engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
      ignore_warnings: true
  phpmd:
      enabled: true
      config:
        file_extensions:
          - php
ratings:
  paths:
  - "**.php"
exclude_paths:
  - test/*
  - vendor/*

